# Basic_Programming_Assingment8

1. Write a Python Program to Add Two Matrices?

In [80]:
import numpy as np

def matAddition(n,d):
    """n represents total matrices to be created; d represents the dimension of each matrix"""
    mat = [] #Creating Empty List to store n matrices and each of dimension dxd
    for i in range(n):
        mat.append(np.random.randint(1,100,(d,d)))
        print(f"Creating mat[{i}] as \n{mat[i]}")
    print(f"The sum is \n{sum(mat)}")
    
matAddition(2,3)

Creating mat[0] as 
[[91  8 40]
 [ 2 35  1]
 [ 1 43 97]]
Creating mat[1] as 
[[16 47 81]
 [51 94 25]
 [48 18  8]]
The sum is 
[[107  55 121]
 [ 53 129  26]
 [ 49  61 105]]


2. Write a Python Program to Multiply Two Matrices?

In [113]:
import numpy as np

def matMultiply():
    mat1 = np.random.randint(2,1000,(3,3))
    mat2 = np.random.randint(1,100,(3,3))
    print(f"The matrix multiplication of \n{mat1} \n\nand \n\n{mat2} \n\nis \n\n{mat1@mat2}")
    
matMultiply()

The matrix multiplication of 
[[627 304 955]
 [311  45 924]
 [587 825 951]] 

and 

[[44  5 12]
 [95 44 90]
 [14 85 79]] 

is 

[[ 69838  97686 110329]
 [ 30895  82075  80778]
 [117517 120070 156423]]


3. Write a Python Program to Transpose a Matrix?

In [127]:
import numpy as np

def matTranspose():
    mat1 =np.random.randint(2,1000,(3,3))
    mat2 = np.ndarray.transpose(mat1)
    print(f"The transpose of \n\n{mat1} is\n\n{mat2}")

matTranspose()

The transpose of 

[[501 332 855]
 [ 74 897 178]
 [364 868 637]] is

[[501  74 364]
 [332 897 868]
 [855 178 637]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [19]:
def wordSort():
    n = int(input("Enter how many words you would like to sort: "))
    inp = []
    i=0
    while i < n:
        inp.append(input("Enter a word: "))
        i = i + 1
    print(f"Your input was {inp}",end=" and after sorting the output is:")
    inp.sort()
    print(inp)

In [18]:
wordSort()

Enter how many words you would like to sort: 2
Enter a word: niraj
Enter a word: kumar
Your input was ['niraj', 'kumar'] and after sorting the output is:['kumar', 'niraj']


5. Write a Python Program to Remove Punctuation From a String?

In [21]:
def removePunctuations():
    inp = input("Enter input string with punctuations: ")
    punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~''' # initializing punctuations string
    print("Your input was "+ inp)
    for ele in inp:
        if ele in punc:
            inp = inp.replace(ele,"")
    print("Your output after removing punctuations is "+inp)

In [23]:
removePunctuations()

Enter input string with punctuations: "iNeuron is the best! There are various course's"
Your input was "iNeuron is the best! There are various course's"
Your output after removing punctuations is iNeuron is the best There are various courses
